In [1]:
import pandas as pd
import numpy as np

df_vendas = pd.read_csv("vendas_tech.csv")
display(df_vendas.head(10)) #imprime os 10 primeiros dados da base de dados
#display(df_vendas.tail(10)) #imprime os 10 ultimos
# df_analise = df_vendas
# df_analise["Data_Base"] = df_analise['Data_Base'].fillna('indisponivel') #adiciono na coluna Data_base indisponiveis nos valores vazios
df_analise = df_vendas.drop(columns=['Data_Base']) #retiro a coluna Data_Base
# df_analise = df_analise.dropna() #Remover linhas com valores vazios:

df_analise['Loja'] = df_analise['Loja'].fillna('Online') #adiciona 'online' nas celulas vazias na coluna loja 
df_analise['Data'] = pd.to_datetime(df_analise['Data'], format='%Y-%m-%d') #padronizaçao de data 
df_analise['Loja'] = df_analise['Loja'].str.strip().str.title() #padronizar os dados da coluna Loja deixando apenas a primeira letra de cada palavra em maiúscula
display(df_analise.head(10))
# O símbolo [:100] significa: do início até a linha 100
df_analise[:100].to_excel("vendas_tech_amostra.xlsx", index=False)

C:\Users\santa\AppData\Local\Temp\ipykernel_1776\3174755809.py:4: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  df_vendas = pd.read_csv("vendas_tech.csv")

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Data_Base
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095,2025-01-01
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750,NaN
2,3,2023-02-25,NaN,"Monitor 27""",1200.0,1,Cliente_14859,NaN
3,4,2024-11-19,RIO DE JANEIRO,Mouse Gamer,120.0,2,Cliente_17343,NaN
4,5,2024-01-27,Rio de Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377,NaN
5,6,2023-03-11,São Paulo,Cabo HDMI,40.0,1,Cliente_24809,NaN
6,7,2024-12-08,Salvador,"Monitor 27""",1200.0,1,Cliente_11076,NaN
7,8,2024-09-12,São Paulo,"Monitor 27""",1200.0,2,Cliente_14053,NaN
8,9,2023-05-20,Belo Horizonte,Mouse Gamer,120.0,1,Cliente_19175,NaN
9,10,2024-10-16,Recife,Notebook HP,3200.0,1,Cliente_13508,NaN

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750
2,3,2023-02-25,Online,"Monitor 27""",1200.0,1,Cliente_14859
3,4,2024-11-19,Rio De Janeiro,Mouse Gamer,120.0,2,Cliente_17343
4,5,2024-01-27,Rio De Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377
5,6,2023-03-11,São Paulo,Cabo HDMI,40.0,1,Cliente_24809
6,7,2024-12-08,Salvador,"Monitor 27""",1200.0,1,Cliente_11076
7,8,2024-09-12,São Paulo,"Monitor 27""",1200.0,2,Cliente_14053
8,9,2023-05-20,Belo Horizonte,Mouse Gamer,120.0,1,Cliente_19175
9,10,2024-10-16,Recife,Notebook HP,3200.0,1,Cliente_13508

In [ ]:
df_analise['Loja'] = df_analise['Loja'].str.strip().str.title() #.str: acessa métodos de manipulação de texto;
#.strip(): remove espaços em branco no início e no fim do texto;
#.title(): coloca a primeira letra de cada palavra em maiúscula.
df_analise = df_analise.drop_duplicates()
df_analise = df_analise.drop_duplicates(subset=['ID_Pedido'], keep='first')

df_analise['forma_venda'] = np.where(
    df_analise['Loja'] == 'Online',
    'Online',
    'Presencial'
)

dic_regioes = {
    'São Paulo': 'Sudeste',
    'Rio De Janeiro': 'Sudeste',
    'Belo Horizonte': 'Sudeste',
    'Salvador': 'Nordeste',
    'Recife': 'Nordeste',
    'Curitiba': 'Sul',
    'Porto Alegre': 'Sul',
    'Online': 'Online'
}

df_analise['regiao'] = df_analise['Loja'].map(dic_regioes)
display(df_analise.head(10))

In [ ]:
df_filtrado = df_analise[
    (df_analise['Produto'] == 'Cabo HDMI') &
    (df_analise['regiao'] == 'Nordeste')
]

df_filtrado2 = df_analise[
    (df_analise['Produto'] == 'Mouse Gamer') |
    (df_analise['regiao'] == 'Nordeste')
]
display(df_filtrado.head(10))
display(df_filtrado2.head(10))

In [ ]:
df_analise['faturamento'] = df_analise['Qtd'] * df_analise['Preco_Unitario']

display(df_analise.head(10))

In [ ]:
df_analise['Loja']

In [ ]:
df_analise[['Loja', 'Produto', 'faturamento']]
df_vendas = df_analise[df_analise['Loja'] == 'Online'] #usado para ver os dados de uma Loja "Sao Paulo"
display(df_vendas.head(10))