In [13]:
import pandas as pd
import numpy as np

df_vendas = pd.read_csv("vendas_tech.csv")
display(df_vendas.head(10)) #imprime os 10 primeiros dados da base de dados
#display(df_vendas.tail(10)) #imprime os 10 ultimos
# df_analise = df_vendas
# df_analise["Data_Base"] = df_analise['Data_Base'].fillna('indisponivel') #adiciono na coluna Data_base indisponiveis nos valores vazios
df_analise = df_vendas.drop(columns=['Data_Base']) #retiro a coluna Data_Base
# df_analise = df_analise.dropna() #Remover linhas com valores vazios:

df_analise['Loja'] = df_analise['Loja'].fillna('Online') #adiciona 'online' nas celulas vazias na coluna loja 
df_analise['Data'] = pd.to_datetime(df_analise['Data'], format='%Y-%m-%d') #padronizaçao de data 
df_analise['Loja'] = df_analise['Loja'].str.strip().str.title() #padronizar os dados da coluna Loja deixando apenas a primeira letra de cada palavra em maiúscula
display(df_analise.head(10))

C:\Users\santa\AppData\Local\Temp\ipykernel_6676\1315129570.py:4: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  df_vendas = pd.read_csv("vendas_tech.csv")

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Data_Base
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095,2025-01-01
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750,NaN
2,3,2023-02-25,NaN,"Monitor 27""",1200.0,1,Cliente_14859,NaN
3,4,2024-11-19,RIO DE JANEIRO,Mouse Gamer,120.0,2,Cliente_17343,NaN
4,5,2024-01-27,Rio de Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377,NaN
5,6,2023-03-11,São Paulo,Cabo HDMI,40.0,1,Cliente_24809,NaN
6,7,2024-12-08,Salvador,"Monitor 27""",1200.0,1,Cliente_11076,NaN
7,8,2024-09-12,São Paulo,"Monitor 27""",1200.0,2,Cliente_14053,NaN
8,9,2023-05-20,Belo Horizonte,Mouse Gamer,120.0,1,Cliente_19175,NaN
9,10,2024-10-16,Recife,Notebook HP,3200.0,1,Cliente_13508,NaN

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750
2,3,2023-02-25,Online,"Monitor 27""",1200.0,1,Cliente_14859
3,4,2024-11-19,Rio De Janeiro,Mouse Gamer,120.0,2,Cliente_17343
4,5,2024-01-27,Rio De Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377
5,6,2023-03-11,São Paulo,Cabo HDMI,40.0,1,Cliente_24809
6,7,2024-12-08,Salvador,"Monitor 27""",1200.0,1,Cliente_11076
7,8,2024-09-12,São Paulo,"Monitor 27""",1200.0,2,Cliente_14053
8,9,2023-05-20,Belo Horizonte,Mouse Gamer,120.0,1,Cliente_19175
9,10,2024-10-16,Recife,Notebook HP,3200.0,1,Cliente_13508

In [ ]:
df_analise['Loja'] = df_analise['Loja'].str.strip().str.title() #.str: acessa métodos de manipulação de texto;
#.strip(): remove espaços em branco no início e no fim do texto;
#.title(): coloca a primeira letra de cada palavra em maiúscula.
df_analise = df_analise.drop_duplicates()
df_analise = df_analise.drop_duplicates(subset=['ID_Pedido'], keep='first')

df_analise['forma_venda'] = np.where(
    df_analise['Loja'] == 'Online',
    'Online',
    'Presencial'
)

dic_regioes = {
    'São Paulo': 'Sudeste',
    'Rio De Janeiro': 'Sudeste',
    'Belo Horizonte': 'Sudeste',
    'Salvador': 'Nordeste',
    'Recife': 'Nordeste',
    'Curitiba': 'Sul',
    'Porto Alegre': 'Sul',
    'Online': 'Online'
}

df_analise['regiao'] = df_analise['Loja'].map(dic_regioes)
display(df_analise.head(10))

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,faturamento,forma_venda,regiao
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095,120.0,Presencial,Sudeste
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750,5500.0,Presencial,Sudeste
2,3,2023-02-25,Online,"Monitor 27""",1200.0,1,Cliente_14859,1200.0,Online,Online
3,4,2024-11-19,Rio De Janeiro,Mouse Gamer,120.0,2,Cliente_17343,240.0,Presencial,Sudeste
4,5,2024-01-27,Rio De Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377,2200.0,Presencial,Sudeste
5,6,2023-03-11,São Paulo,Cabo HDMI,40.0,1,Cliente_24809,40.0,Presencial,Sudeste
6,7,2024-12-08,Salvador,"Monitor 27""",1200.0,1,Cliente_11076,1200.0,Presencial,Nordeste
7,8,2024-09-12,São Paulo,"Monitor 27""",1200.0,2,Cliente_14053,2400.0,Presencial,Sudeste
8,9,2023-05-20,Belo Horizonte,Mouse Gamer,120.0,1,Cliente_19175,120.0,Presencial,Sudeste
9,10,2024-10-16,Recife,Notebook HP,3200.0,1,Cliente_13508,3200.0,Presencial,Nordeste

In [47]:
df_filtrado = df_analise[
    (df_analise['Produto'] == 'Cabo HDMI') &
    (df_analise['regiao'] == 'Nordeste')
]

df_filtrado2 = df_analise[
    (df_analise['Produto'] == 'Mouse Gamer') |
    (df_analise['regiao'] == 'Nordeste')
]
display(df_filtrado.head(10))
display(df_filtrado2.head(10))

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,faturamento,forma_venda,regiao
18,19,2024-03-20,Salvador,Cabo HDMI,40.0,1,Cliente_4793,40.0,Presencial,Nordeste
23,24,2023-05-15,Recife,Cabo HDMI,40.0,3,Cliente_20951,120.0,Presencial,Nordeste
46,47,2023-07-24,Recife,Cabo HDMI,40.0,1,Cliente_2518,40.0,Presencial,Nordeste
83,84,2024-03-23,Recife,Cabo HDMI,40.0,1,Cliente_13740,40.0,Presencial,Nordeste
112,113,2023-08-09,Salvador,Cabo HDMI,40.0,1,Cliente_26435,40.0,Presencial,Nordeste
118,119,2023-10-11,Salvador,Cabo HDMI,40.0,1,Cliente_9695,40.0,Presencial,Nordeste
120,121,2024-02-28,Recife,Cabo HDMI,40.0,1,Cliente_15384,40.0,Presencial,Nordeste
140,141,2023-09-19,Recife,Cabo HDMI,40.0,1,Cliente_18928,40.0,Presencial,Nordeste
143,144,2024-04-18,Recife,Cabo HDMI,40.0,3,Cliente_16085,120.0,Presencial,Nordeste
218,219,2023-04-04,Salvador,Cabo HDMI,40.0,5,Cliente_23031,200.0,Presencial,Nordeste

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,faturamento,forma_venda,regiao
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095,120.0,Presencial,Sudeste
3,4,2024-11-19,Rio De Janeiro,Mouse Gamer,120.0,2,Cliente_17343,240.0,Presencial,Sudeste
6,7,2024-12-08,Salvador,"Monitor 27""",1200.0,1,Cliente_11076,1200.0,Presencial,Nordeste
8,9,2023-05-20,Belo Horizonte,Mouse Gamer,120.0,1,Cliente_19175,120.0,Presencial,Sudeste
9,10,2024-10-16,Recife,Notebook HP,3200.0,1,Cliente_13508,3200.0,Presencial,Nordeste
11,12,2024-01-29,Rio De Janeiro,Mouse Gamer,120.0,1,Cliente_586,120.0,Presencial,Sudeste
12,13,2024-06-25,Recife,Smartphone Samsung,2200.0,1,Cliente_4301,2200.0,Presencial,Nordeste
18,19,2024-03-20,Salvador,Cabo HDMI,40.0,1,Cliente_4793,40.0,Presencial,Nordeste
23,24,2023-05-15,Recife,Cabo HDMI,40.0,3,Cliente_20951,120.0,Presencial,Nordeste
29,30,2023-03-18,Recife,iPhone 14,5500.0,5,Cliente_25098,27500.0,Presencial,Nordeste

In [43]:
df_analise['faturamento'] = df_analise['Qtd'] * df_analise['Preco_Unitario']

display(df_analise.head(10))

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,faturamento,forma_venda,regiao
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095,120.0,Presencial,Sudeste
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750,5500.0,Presencial,Sudeste
2,3,2023-02-25,Online,"Monitor 27""",1200.0,1,Cliente_14859,1200.0,Online,Online
3,4,2024-11-19,Rio De Janeiro,Mouse Gamer,120.0,2,Cliente_17343,240.0,Presencial,Sudeste
4,5,2024-01-27,Rio De Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377,2200.0,Presencial,Sudeste
5,6,2023-03-11,São Paulo,Cabo HDMI,40.0,1,Cliente_24809,40.0,Presencial,Sudeste
6,7,2024-12-08,Salvador,"Monitor 27""",1200.0,1,Cliente_11076,1200.0,Presencial,Nordeste
7,8,2024-09-12,São Paulo,"Monitor 27""",1200.0,2,Cliente_14053,2400.0,Presencial,Sudeste
8,9,2023-05-20,Belo Horizonte,Mouse Gamer,120.0,1,Cliente_19175,120.0,Presencial,Sudeste
9,10,2024-10-16,Recife,Notebook HP,3200.0,1,Cliente_13508,3200.0,Presencial,Nordeste

In [28]:
df_analise['Loja']

0              São Paulo
1         Belo Horizonte
2                 Online
3         Rio De Janeiro
4         Rio De Janeiro
               ...
100095      Porto Alegre
100096      Porto Alegre
100097    Belo Horizonte
100098          Salvador
100099         São Paulo
Name: Loja, Length: 100100, dtype: object

In [ ]:
df_analise[['Loja', 'Produto', 'faturamento']]
df_vendas = df_analise[df_analise['Loja'] == 'Online'] #usado para ver os dados de uma Loja "Sao Paulo"
display(df_vendas.head(10))

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,faturamento
2,3,2023-02-25,Online,"Monitor 27""",1200.0,1,Cliente_14859,1200.0
64,65,2024-04-17,Online,Mouse Gamer,120.0,2,Cliente_2365,240.0
171,172,2023-01-14,Online,"Monitor 27""",1200.0,1,Cliente_27087,1200.0
173,174,2023-01-22,Online,iPhone 14,5500.0,1,Cliente_16918,5500.0
276,277,2024-09-09,Online,Notebook Dell,3500.0,3,Cliente_12507,10500.0
464,465,2024-03-31,Online,iPhone 14,5500.0,1,Cliente_28133,5500.0
540,541,2024-07-19,Online,Mouse Gamer,120.0,1,Cliente_3294,120.0
607,608,2023-10-31,Online,Cabo HDMI,40.0,1,Cliente_1725,40.0
670,671,2023-12-03,Online,Notebook Dell,3500.0,1,Cliente_24707,3500.0
688,689,2024-11-04,Online,Mouse Gamer,120.0,1,Cliente_412,120.0